//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.07 at 05:01:05 AM BDT 
//


package bd.ac.du.iit.onestopcitizenservice.commonservice.interfaces;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="code"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="RC: 200"/&gt;
 *     &lt;enumeration value="RC: 201"/&gt;
 *     &lt;enumeration value="RC: 204"/&gt;
 *     &lt;enumeration value="RC: 400"/&gt;
 *     &lt;enumeration value="RC: 450"/&gt;
 *     &lt;enumeration value="RC: 498"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "code")
@XmlEnum
public enum Code {

    @XmlEnumValue("RC: 200")
    RC_200("RC: 200"),
    @XmlEnumValue("RC: 201")
    RC_201("RC: 201"),
    @XmlEnumValue("RC: 204")
    RC_204("RC: 204"),
    @XmlEnumValue("RC: 400")
    RC_400("RC: 400"),
    @XmlEnumValue("RC: 450")
    RC_450("RC: 450"),
    @XmlEnumValue("RC: 498")
    RC_498("RC: 498");
    private final String value;

    Code(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Code fromValue(String v) {
        for (Code c: Code.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
