//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.09 at 02:11:13 AM BDT 
//


package bd.ac.du.iit.onestopcitizenservice.citizencontactservice.interfaces;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for columnToBeSorted.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="columnToBeSorted"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Name"/&gt;
 *     &lt;enumeration value="Category"/&gt;
 *     &lt;enumeration value="Contact No"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "columnToBeSorted")
@XmlEnum
public enum ColumnToBeSorted {

    @XmlEnumValue("Name")
    NAME("Name"),
    @XmlEnumValue("Category")
    CATEGORY("Category"),
    @XmlEnumValue("Contact No")
    CONTACT_NO("Contact No");
    private final String value;

    ColumnToBeSorted(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ColumnToBeSorted fromValue(String v) {
        for (ColumnToBeSorted c: ColumnToBeSorted.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
