//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.09 at 02:11:13 AM BDT 
//


package bd.ac.du.iit.onestopcitizenservice.searchandsortservice.interfaces;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bd.ac.du.iit.onestopcitizenservice.searchandsortservice.interfaces package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bd.ac.du.iit.onestopcitizenservice.searchandsortservice.interfaces
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ValidationWithSearchByNameRequest }
     * 
     */
    public ValidationWithSearchByNameRequest createValidationWithSearchByNameRequest() {
        return new ValidationWithSearchByNameRequest();
    }

    /**
     * Create an instance of {@link ValidationWithSearchByNameResponse }
     * 
     */
    public ValidationWithSearchByNameResponse createValidationWithSearchByNameResponse() {
        return new ValidationWithSearchByNameResponse();
    }

    /**
     * Create an instance of {@link ValidationWithSearchByCategoryRequest }
     * 
     */
    public ValidationWithSearchByCategoryRequest createValidationWithSearchByCategoryRequest() {
        return new ValidationWithSearchByCategoryRequest();
    }

    /**
     * Create an instance of {@link ValidationWithSearchByCategoryResponse }
     * 
     */
    public ValidationWithSearchByCategoryResponse createValidationWithSearchByCategoryResponse() {
        return new ValidationWithSearchByCategoryResponse();
    }

    /**
     * Create an instance of {@link ValidationWithSearchByContactRequest }
     * 
     */
    public ValidationWithSearchByContactRequest createValidationWithSearchByContactRequest() {
        return new ValidationWithSearchByContactRequest();
    }

    /**
     * Create an instance of {@link ValidationWithSearchByContactResponse }
     * 
     */
    public ValidationWithSearchByContactResponse createValidationWithSearchByContactResponse() {
        return new ValidationWithSearchByContactResponse();
    }

}
