//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.07 at 05:01:05 AM BDT 
//


package bd.ac.du.iit.onestopcitizenservice.citizencontactservice.interfaces;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for category.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="category"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Education"/&gt;
 *     &lt;enumeration value="Environment"/&gt;
 *     &lt;enumeration value="Health"/&gt;
 *     &lt;enumeration value="Miscellaneous"/&gt;
 *     &lt;enumeration value="National"/&gt;
 *     &lt;enumeration value="Security"/&gt;
 *     &lt;enumeration value="Woman and child"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "category")
@XmlEnum
public enum Category {

    @XmlEnumValue("Education")
    EDUCATION("Education"),
    @XmlEnumValue("Environment")
    ENVIRONMENT("Environment"),
    @XmlEnumValue("Health")
    HEALTH("Health"),
    @XmlEnumValue("Miscellaneous")
    MISCELLANEOUS("Miscellaneous"),
    @XmlEnumValue("National")
    NATIONAL("National"),
    @XmlEnumValue("Security")
    SECURITY("Security"),
    @XmlEnumValue("Woman and child")
    WOMAN_AND_CHILD("Woman and child");
    private final String value;

    Category(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Category fromValue(String v) {
        for (Category c: Category.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
