//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.07 at 05:01:05 AM BDT 
//


package bd.ac.du.iit.onestopcitizenservice.citizencontactservice.interfaces;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bd.ac.du.iit.onestopcitizenservice.citizencontactservice.interfaces package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bd.ac.du.iit.onestopcitizenservice.citizencontactservice.interfaces
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddContactRequest }
     * 
     */
    public AddContactRequest createAddContactRequest() {
        return new AddContactRequest();
    }

    /**
     * Create an instance of {@link ContactDetails }
     * 
     */
    public ContactDetails createContactDetails() {
        return new ContactDetails();
    }

    /**
     * Create an instance of {@link AddContactResponse }
     * 
     */
    public AddContactResponse createAddContactResponse() {
        return new AddContactResponse();
    }

    /**
     * Create an instance of {@link GetContactRequest }
     * 
     */
    public GetContactRequest createGetContactRequest() {
        return new GetContactRequest();
    }

    /**
     * Create an instance of {@link GetContactResponse }
     * 
     */
    public GetContactResponse createGetContactResponse() {
        return new GetContactResponse();
    }

    /**
     * Create an instance of {@link GetAllContactsRequest }
     * 
     */
    public GetAllContactsRequest createGetAllContactsRequest() {
        return new GetAllContactsRequest();
    }

    /**
     * Create an instance of {@link GetAllContactsResponse }
     * 
     */
    public GetAllContactsResponse createGetAllContactsResponse() {
        return new GetAllContactsResponse();
    }

    /**
     * Create an instance of {@link ContactList }
     * 
     */
    public ContactList createContactList() {
        return new ContactList();
    }

    /**
     * Create an instance of {@link UpdateContactRequest }
     * 
     */
    public UpdateContactRequest createUpdateContactRequest() {
        return new UpdateContactRequest();
    }

    /**
     * Create an instance of {@link UpdateContactResponse }
     * 
     */
    public UpdateContactResponse createUpdateContactResponse() {
        return new UpdateContactResponse();
    }

    /**
     * Create an instance of {@link DeleteContactRequest }
     * 
     */
    public DeleteContactRequest createDeleteContactRequest() {
        return new DeleteContactRequest();
    }

    /**
     * Create an instance of {@link DeleteContactResponse }
     * 
     */
    public DeleteContactResponse createDeleteContactResponse() {
        return new DeleteContactResponse();
    }

    /**
     * Create an instance of {@link SearchByNameRequest }
     * 
     */
    public SearchByNameRequest createSearchByNameRequest() {
        return new SearchByNameRequest();
    }

    /**
     * Create an instance of {@link SearchByNameDetails }
     * 
     */
    public SearchByNameDetails createSearchByNameDetails() {
        return new SearchByNameDetails();
    }

    /**
     * Create an instance of {@link SearchByNameResponse }
     * 
     */
    public SearchByNameResponse createSearchByNameResponse() {
        return new SearchByNameResponse();
    }

    /**
     * Create an instance of {@link SearchByCategoryRequest }
     * 
     */
    public SearchByCategoryRequest createSearchByCategoryRequest() {
        return new SearchByCategoryRequest();
    }

    /**
     * Create an instance of {@link SearchByCategoryDetails }
     * 
     */
    public SearchByCategoryDetails createSearchByCategoryDetails() {
        return new SearchByCategoryDetails();
    }

    /**
     * Create an instance of {@link SearchByCategoryResponse }
     * 
     */
    public SearchByCategoryResponse createSearchByCategoryResponse() {
        return new SearchByCategoryResponse();
    }

    /**
     * Create an instance of {@link SearchByContactRequest }
     * 
     */
    public SearchByContactRequest createSearchByContactRequest() {
        return new SearchByContactRequest();
    }

    /**
     * Create an instance of {@link SearchByContactDetails }
     * 
     */
    public SearchByContactDetails createSearchByContactDetails() {
        return new SearchByContactDetails();
    }

    /**
     * Create an instance of {@link SearchByContactResponse }
     * 
     */
    public SearchByContactResponse createSearchByContactResponse() {
        return new SearchByContactResponse();
    }

}
