//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.07 at 02:11:53 AM BDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://iit.du.ac.bd/onestopcitizenservice/sessionvalidatorservice/interfaces", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bd.ac.du.iit.onestopcitizenservice.sessionvalidatorservice.interfaces;
