//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.07 at 02:11:53 AM BDT 
//


package bd.ac.du.iit.onestopcitizenservice.userservice.interfaces;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="loginWithMobileNoDetails" type="{http://iit.du.ac.bd/onestopcitizenservice/userservice/interfaces}loginWithMobileNoDetails"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "loginWithMobileNoDetails"
})
@XmlRootElement(name = "loginWithMobileNoRequest")
public class LoginWithMobileNoRequest {

    @XmlElement(required = true)
    protected LoginWithMobileNoDetails loginWithMobileNoDetails;

    /**
     * Gets the value of the loginWithMobileNoDetails property.
     * 
     * @return
     *     possible object is
     *     {@link LoginWithMobileNoDetails }
     *     
     */
    public LoginWithMobileNoDetails getLoginWithMobileNoDetails() {
        return loginWithMobileNoDetails;
    }

    /**
     * Sets the value of the loginWithMobileNoDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoginWithMobileNoDetails }
     *     
     */
    public void setLoginWithMobileNoDetails(LoginWithMobileNoDetails value) {
        this.loginWithMobileNoDetails = value;
    }

}
